### PR TITLE
(gabriel bb/xvfb action#17) configurable server options

### PR DESCRIPTION
**Pull request by s1hofmann**

### CODE REVIEW

**Comment by sclassen** [comment]
@GabrielBB would love to see this getting merged

**Comment by s1hofmann** [comment]
Closes #17

**Comment by GabrielBB** [comment]
@s1hofmann Wow you opened this a long time ago, I'm sorry. I have to check my notification settings, somehow I stopped getting notifications for this repo. I will comment again here after releasing today

**Comment by s1hofmann** [comment]
@GabrielBB No worries, happens to all of us! Thanks for merging! 👍

**Pull request merged**
