### PR TITLE
Update node to 16

### PR DESCRIPTION
**Pull request by hankolsen**
Update action.yml to use node 16. 
Solves #30

### CODE REVIEW

**Comment by julianhille** [comment]
Until this is merged and to get rid of the deprecation message one could replace `GabrielBB/xvfb-action@v1` with `hankolsen/xvfb-action@dcb076c1c3802845f73bb6fe14a009d8d3377255`

**Comment by booo** [comment]
I would appreciate a new release with this fix in it.

**Comment by julianhille** [comment]
Me too.

**Review by apupier — APPROVED** [review]

**Comment by alisonatwork** [comment]
I posted another possible solution for this on #30 - since the `ubuntu-latest` image now has `xvfb-run` inside it, you can probably skip using this project altogether and just the regular Linux container.

**Comment by booo** [comment]
@alisonatwork thanks for pointing out this fix! I will implement this in our project.

**Comment by julianhille** [comment]
> I posted another possible solution for this on #30 - since the `ubuntu-latest` image now has `xvfb-run` inside it, you can probably skip this project altogether and just run your tests in the regular Linux container.

just want to point out that this might not be a solution for all, as ubuntu-latest brings a new glibc / libc with it and so raises libc requirements for compiled binaries.
May need splitting compiling and testing onto two different machines in different build steps.

Just realised it when i wanted to start to update to this solution.

**Comment by GabrielBB** [comment]
Thank you. But this repo is now deprecated, please switch to: https://github.com/coactions/setup-xvfb

**Pull request closed without merging**
